services:
  web:
    build:
     # We are using the created dockerfile
      dockerfile: Dockerfile
     # We are using ports 8000 both on host and on the server
    ports:
      - "8000:8000"
     # Mounting our Current Working Directory
    volumes:
      - ".:${CWD:-/code}"
      # - /code/static
